DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NAMES TEXT NOT NULL,
  POWER TEXT NOT NULL
)

INSERT INTO TB_HEROES (NAMES, POWER)
VALUES
  ("BATMAN", "MONEY"),
  ("SPIDER-MAN", "CRAZY"),
  ("AQUAMAN", "WATER")