DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NAMES TEXT NOT NULL,
  POWER TEXT NOT NULL
)

--create
INSERT INTO TB_HEROES (NAMES, POWER)
VALUES
  ("BATMAN", "MONEY"),
  ("SPIDER-MAN", "CRAZY"),
  ("AQUAMAN", "WATER")

--READ
SELECT * FROM TB_HEROES;
SELECT * FROM TB_HEROES WHERE NAMES = 'SPIDER-MAN'

--UPDATE
UPDATE TB_HEROES
  SET NAMES = 'GOKU', POWER = 'GOD'
  WHERE ID = 1;

--DELETE
DELETE FROM TB_HEROES WHERE ID = 3;